name: Latest Medium Articles

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-medium-articles:
    name: Update README with Medium posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          feed_list: "https://medium.com/feed/@gregorisbachtsevanos"
